-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.agent_calls (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid,
  lead_id uuid,
  campaign_id uuid,
  ai_call_log_id uuid,
  agent_id uuid,
  agent_name text,
  call_sid text,
  started_at timestamp with time zone DEFAULT now(),
  ended_at timestamp with time zone,
  duration integer,
  recording_url text,
  transcript text,
  outcome text,
  next_action text,
  next_action_date timestamp with time zone,
  agent_notes text,
  sentiment_score numeric,
  interest_level text,
  objections jsonb DEFAULT '[]'::jsonb,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT agent_calls_pkey PRIMARY KEY (id),
  CONSTRAINT agent_calls_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT agent_calls_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES public.leads(id),
  CONSTRAINT agent_calls_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id),
  CONSTRAINT agent_calls_ai_call_log_id_fkey FOREIGN KEY (ai_call_log_id) REFERENCES public.call_logs(id),
  CONSTRAINT agent_calls_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.audit_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid,
  user_id uuid,
  user_name text,
  action text NOT NULL,
  entity_type text,
  entity_id uuid,
  metadata jsonb,
  impersonator_user_id uuid,
  is_impersonated boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT audit_logs_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT audit_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.billing_invoices (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  invoice_number text NOT NULL UNIQUE,
  billing_period_start timestamp with time zone NOT NULL,
  billing_period_end timestamp with time zone NOT NULL,
  subscription_amount numeric DEFAULT 0,
  credits_amount numeric DEFAULT 0,
  subtotal numeric NOT NULL,
  tax_percentage numeric DEFAULT 18.00,
  tax_amount numeric NOT NULL DEFAULT 0,
  total_amount numeric NOT NULL,
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'issued'::text, 'paid'::text, 'overdue'::text, 'cancelled'::text, 'refunded'::text])),
  due_date timestamp with time zone NOT NULL,
  paid_at timestamp with time zone,
  payment_method text,
  payment_reference text,
  line_items jsonb NOT NULL DEFAULT '[]'::jsonb,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT billing_invoices_pkey PRIMARY KEY (id),
  CONSTRAINT billing_invoices_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.billing_plans (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  description text,
  module_type text NOT NULL CHECK (module_type = ANY (ARRAY['crm'::text, 'inventory'::text, 'analytics'::text, 'all_modules'::text])),
  base_price_inr numeric NOT NULL DEFAULT 0,
  per_user_price_inr numeric NOT NULL,
  discount_percentage numeric DEFAULT 0,
  features jsonb DEFAULT '{}'::jsonb,
  max_users integer,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  max_projects integer,
  max_leads integer,
  allowed_modules ARRAY DEFAULT ARRAY['crm'::text],
  CONSTRAINT billing_plans_pkey PRIMARY KEY (id)
);
CREATE TABLE public.call_credits (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL UNIQUE,
  balance numeric NOT NULL DEFAULT 0 CHECK (balance >= 0::numeric),
  total_purchased numeric NOT NULL DEFAULT 0,
  total_consumed numeric NOT NULL DEFAULT 0,
  low_balance_threshold numeric DEFAULT 10.0,
  last_recharged_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT call_credits_pkey PRIMARY KEY (id),
  CONSTRAINT call_credits_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.call_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid,
  lead_id uuid,
  campaign_id uuid,
  caller_id uuid,
  status text,
  duration integer DEFAULT 0,
  recording_url text,
  ai_analysis jsonb,
  created_at timestamp with time zone DEFAULT now(),
  call_sid text UNIQUE,
  project_id uuid,
  direction text DEFAULT 'outbound'::text,
  caller_number text,
  callee_number text,
  metadata jsonb,
  call_status text,
  notes text,
  transferred boolean DEFAULT false,
  transferred_at timestamp with time zone,
  transfer_reason text,
  transfer_department text,
  disconnect_reason text,
  disconnect_notes text,
  ended_at timestamp with time zone,
  conversation_transcript text,
  sentiment_score numeric,
  interest_level text,
  summary text,
  call_cost numeric,
  ai_metadata jsonb,
  archived_at timestamp with time zone,
  archived_by uuid,
  CONSTRAINT call_logs_pkey PRIMARY KEY (id),
  CONSTRAINT call_logs_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT call_logs_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES public.leads(id),
  CONSTRAINT call_logs_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id),
  CONSTRAINT call_logs_caller_id_fkey FOREIGN KEY (caller_id) REFERENCES auth.users(id),
  CONSTRAINT call_logs_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT call_logs_archived_by_fkey FOREIGN KEY (archived_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.call_queue (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  campaign_id uuid,
  lead_id uuid,
  organization_id uuid,
  status USER-DEFINED DEFAULT 'queued'::queue_status,
  attempt_count integer DEFAULT 0,
  max_attempts integer DEFAULT 3,
  next_retry_at timestamp with time zone DEFAULT now(),
  last_error text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT call_queue_pkey PRIMARY KEY (id),
  CONSTRAINT call_queue_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id),
  CONSTRAINT call_queue_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES public.leads(id),
  CONSTRAINT call_queue_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.campaigns (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid,
  project_id uuid,
  name text NOT NULL,
  description text,
  status text DEFAULT 'draft'::text,
  start_date date,
  end_date date,
  time_start time without time zone,
  time_end time without time zone,
  metadata jsonb,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  total_calls integer DEFAULT 0,
  answered_calls integer DEFAULT 0,
  transferred_calls integer DEFAULT 0,
  avg_sentiment_score numeric,
  manual_start boolean NOT NULL DEFAULT false,
  ai_script text,
  call_settings jsonb DEFAULT '{"language":"hinglish","voice_id":"shimmer","max_duration":600,"silence_timeout":30}'::jsonb,
  archived_at timestamp with time zone,
  archived_by uuid,
  CONSTRAINT campaigns_pkey PRIMARY KEY (id),
  CONSTRAINT campaigns_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT campaigns_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT campaigns_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT campaigns_archived_by_fkey FOREIGN KEY (archived_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.conversation_insights (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid,
  call_log_id uuid,
  lead_id uuid,
  overall_sentiment numeric,
  sentiment_label text,
  primary_emotion text,
  intent text,
  interest_level text,
  objections jsonb DEFAULT '[]'::jsonb,
  budget_mentioned boolean DEFAULT false,
  budget_range text,
  timeline_mentioned boolean DEFAULT false,
  timeline text,
  key_phrases jsonb DEFAULT '[]'::jsonb,
  recommended_action text,
  priority_score integer,
  analyzed_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  purchase_readiness text,
  CONSTRAINT conversation_insights_pkey PRIMARY KEY (id),
  CONSTRAINT conversation_insights_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT conversation_insights_call_log_id_fkey FOREIGN KEY (call_log_id) REFERENCES public.call_logs(id),
  CONSTRAINT conversation_insights_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES public.leads(id)
);
CREATE TABLE public.country_pricing (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  country_code text NOT NULL UNIQUE,
  country_name text NOT NULL,
  currency_code text NOT NULL,
  per_user_monthly_rate numeric NOT NULL,
  call_credit_rate numeric NOT NULL,
  exchange_rate_to_inr numeric NOT NULL DEFAULT 1.0000,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT country_pricing_pkey PRIMARY KEY (id)
);
CREATE TABLE public.credit_transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  transaction_type text NOT NULL CHECK (transaction_type = ANY (ARRAY['purchase'::text, 'consumption'::text, 'refund'::text, 'adjustment'::text])),
  amount numeric NOT NULL,
  balance_before numeric NOT NULL,
  balance_after numeric NOT NULL,
  reference_type text,
  reference_id uuid,
  description text,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT credit_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT credit_transactions_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.dashboard_features (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  feature_key character varying NOT NULL UNIQUE,
  feature_name character varying NOT NULL,
  description text,
  category character varying,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT dashboard_features_pkey PRIMARY KEY (id)
);
CREATE TABLE public.dashboard_role_permissions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  organization_id uuid,
  role character varying NOT NULL,
  feature_key character varying,
  is_enabled boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT dashboard_role_permissions_pkey PRIMARY KEY (id),
  CONSTRAINT dashboard_role_permissions_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT dashboard_role_permissions_feature_key_fkey FOREIGN KEY (feature_key) REFERENCES public.dashboard_features(feature_key)
);
CREATE TABLE public.dashboard_user_permissions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  feature_key character varying NOT NULL,
  is_enabled boolean DEFAULT true,
  granted_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT dashboard_user_permissions_pkey PRIMARY KEY (id),
  CONSTRAINT dashboard_user_permissions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT dashboard_user_permissions_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT dashboard_user_permissions_feature_key_fkey FOREIGN KEY (feature_key) REFERENCES public.dashboard_features(feature_key),
  CONSTRAINT dashboard_user_permissions_granted_by_fkey FOREIGN KEY (granted_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.deals (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  lead_id uuid NOT NULL,
  unit_id uuid,
  organization_id uuid NOT NULL,
  name text NOT NULL,
  amount numeric,
  stage text,
  probability integer CHECK (probability >= 0 AND probability <= 100),
  status text DEFAULT 'active'::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  close_date timestamp with time zone,
  project_id uuid,
  created_by uuid,
  CONSTRAINT deals_pkey PRIMARY KEY (id),
  CONSTRAINT deals_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES public.leads(id),
  CONSTRAINT deals_property_id_fkey FOREIGN KEY (unit_id) REFERENCES public.units(id),
  CONSTRAINT deals_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT deals_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT deals_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.follow_up_tasks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid,
  lead_id uuid,
  campaign_id uuid,
  assigned_to uuid,
  created_by uuid,
  task_type text NOT NULL,
  title text NOT NULL,
  description text,
  priority text NOT NULL DEFAULT 'medium'::text,
  due_date timestamp with time zone NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text,
  completed_at timestamp with time zone,
  context text,
  ai_suggestion text,
  source text DEFAULT 'manual'::text,
  outcome text,
  outcome_notes text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT follow_up_tasks_pkey PRIMARY KEY (id),
  CONSTRAINT follow_up_tasks_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT follow_up_tasks_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES public.leads(id),
  CONSTRAINT follow_up_tasks_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id),
  CONSTRAINT follow_up_tasks_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES public.profiles(id),
  CONSTRAINT follow_up_tasks_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.impersonation_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  admin_id uuid,
  target_user_id uuid,
  reason text,
  active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  ended_at timestamp with time zone,
  CONSTRAINT impersonation_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT impersonation_sessions_admin_id_fkey FOREIGN KEY (admin_id) REFERENCES auth.users(id),
  CONSTRAINT impersonation_sessions_target_user_id_fkey FOREIGN KEY (target_user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.integrations_config (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  integration_id text NOT NULL,
  config jsonb DEFAULT '{}'::jsonb,
  is_active boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT integrations_config_pkey PRIMARY KEY (id),
  CONSTRAINT integrations_config_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.invoices (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  subscription_id uuid,
  organization_id uuid NOT NULL,
  amount numeric NOT NULL,
  currency text DEFAULT 'INR'::text,
  status USER-DEFINED DEFAULT 'draft'::invoice_status,
  invoice_number text UNIQUE,
  invoice_date date DEFAULT CURRENT_DATE,
  due_date date,
  paid_at timestamp with time zone,
  payment_method_id uuid,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT invoices_pkey PRIMARY KEY (id),
  CONSTRAINT invoices_subscription_id_fkey FOREIGN KEY (subscription_id) REFERENCES public.subscriptions(id),
  CONSTRAINT invoices_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT invoices_payment_method_id_fkey FOREIGN KEY (payment_method_id) REFERENCES public.payment_methods(id)
);
CREATE TABLE public.lead_activities (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid,
  lead_id uuid,
  type text NOT NULL,
  content jsonb DEFAULT '{}'::jsonb,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT lead_activities_pkey PRIMARY KEY (id),
  CONSTRAINT lead_activities_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT lead_activities_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES public.leads(id),
  CONSTRAINT lead_activities_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.lead_documents (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  lead_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  file_name text NOT NULL,
  file_url text NOT NULL,
  file_type text,
  file_size integer,
  document_type text CHECK (document_type = ANY (ARRAY['proposal'::text, 'contract'::text, 'brochure'::text, 'presentation'::text, 'other'::text])),
  uploaded_by uuid,
  uploaded_at timestamp with time zone DEFAULT now(),
  CONSTRAINT lead_documents_pkey PRIMARY KEY (id),
  CONSTRAINT lead_documents_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES public.leads(id),
  CONSTRAINT lead_documents_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT lead_documents_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES auth.users(id)
);
CREATE TABLE public.lead_forms (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  organization_id uuid,
  project_id uuid,
  campaign_id uuid,
  name text NOT NULL,
  schema jsonb NOT NULL DEFAULT '[]'::jsonb,
  is_active boolean DEFAULT true,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT lead_forms_pkey PRIMARY KEY (id),
  CONSTRAINT lead_forms_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT lead_forms_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT lead_forms_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id),
  CONSTRAINT lead_forms_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.lead_interactions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  lead_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  type text NOT NULL CHECK (type = ANY (ARRAY['email'::text, 'call'::text, 'meeting'::text, 'note'::text, 'sms'::text, 'whatsapp'::text])),
  direction text CHECK (direction = ANY (ARRAY['inbound'::text, 'outbound'::text])),
  subject text,
  content text,
  duration integer,
  outcome text,
  email_opened boolean DEFAULT false,
  email_clicked boolean DEFAULT false,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT lead_interactions_pkey PRIMARY KEY (id),
  CONSTRAINT lead_interactions_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES public.leads(id),
  CONSTRAINT lead_interactions_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT lead_interactions_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
-- lead_profiles table has been merged into leads (see latest_migartion.sql)
CREATE TABLE public.lead_tags (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  lead_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  tag text NOT NULL,
  color text DEFAULT '#6B7280'::text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT lead_tags_pkey PRIMARY KEY (id),
  CONSTRAINT lead_tags_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES public.leads(id),
  CONSTRAINT lead_tags_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.lead_tasks (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  lead_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  title text NOT NULL,
  description text,
  due_date timestamp with time zone,
  priority text DEFAULT 'medium'::text CHECK (priority = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text])),
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'completed'::text, 'overdue'::text])),
  assigned_to uuid,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  completed_at timestamp with time zone,
  due_time text,
  CONSTRAINT lead_tasks_pkey PRIMARY KEY (id),
  CONSTRAINT lead_tasks_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES public.leads(id),
  CONSTRAINT lead_tasks_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT lead_tasks_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES auth.users(id),
  CONSTRAINT lead_tasks_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.leads (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid,
  project_id uuid,
  name text NOT NULL,
  email text,
  phone text,
  source text DEFAULT 'manual'::text,
  notes text,
  call_log_id uuid,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  metadata jsonb,
  -- AI agent / call outcomes (written by vantage-webserver)
  transferred_to_human boolean DEFAULT false,
  rejection_reason text,
  abuse_flag boolean DEFAULT false,
  abuse_details text,
  waiting_status text,            -- 'callback_scheduled' | null
  callback_time timestamp with time zone,
  -- Lead identity extras
  mobile text,
  avatar_url text,
  external_lead_id text,
  raw_data jsonb DEFAULT '{}'::jsonb,
  -- Pipeline
  stage_id uuid NOT NULL,
  assigned_to uuid,
  -- AI intelligence (updated after every call)
  score integer DEFAULT 0,
  last_contacted_at timestamp with time zone,
  interest_level text,            -- 'high' | 'medium' | 'low' | 'none'
  purchase_readiness text,        -- AI-assessed readiness
  budget_range text,              -- AI-estimated budget from call transcript (free-text)
  last_sentiment_score numeric,   -- -1.0 to 1.0
  total_calls integer DEFAULT 0,
  -- Professional info (merged from lead_profiles)
  company text,
  job_title text,
  industry text,
  department text,
  -- Address (merged from lead_profiles)
  mailing_street text,
  mailing_city text,
  mailing_state text,
  mailing_zip text,
  mailing_country text,
  -- Client preferences (structured — matches inventory config form)
  preferred_category text CHECK (preferred_category = ANY (ARRAY['residential'::text, 'commercial'::text, 'land'::text])),
  preferred_property_type text,
  preferred_configuration text,
  preferred_transaction_type text CHECK (preferred_transaction_type = ANY (ARRAY['sell'::text, 'rent'::text, 'lease'::text])),
  -- Purchase intent (structured)
  preferred_location text,
  preferred_timeline text,
  min_budget numeric,
  max_budget numeric,
  -- Call context / behavioral (AI-written after calls)
  pain_points text[],
  competitor_mentions text[],
  preferred_contact_method text,
  best_contact_time text,
  -- Extensibility
  custom_fields jsonb DEFAULT '{}'::jsonb,
  -- Archival
  archived_at timestamp with time zone,
  archived_by uuid,
  CONSTRAINT leads_pkey PRIMARY KEY (id),
  CONSTRAINT leads_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT leads_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT leads_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT leads_stage_id_fkey FOREIGN KEY (stage_id) REFERENCES public.pipeline_stages(id),
  CONSTRAINT leads_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES public.profiles(id),
  CONSTRAINT leads_archived_by_fkey FOREIGN KEY (archived_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  type text NOT NULL CHECK (type = ANY (ARRAY['info'::text, 'warning'::text, 'success'::text, 'error'::text])),
  title text NOT NULL,
  message text NOT NULL,
  link text,
  is_read boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.organization_addons (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  addon_id uuid NOT NULL,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'cancelled'::text, 'suspended'::text])),
  started_at timestamp with time zone DEFAULT now(),
  cancelled_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT organization_addons_pkey PRIMARY KEY (id),
  CONSTRAINT organization_addons_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT organization_addons_addon_id_fkey FOREIGN KEY (addon_id) REFERENCES public.subscription_addons(id)
);
CREATE TABLE public.organization_subscriptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL UNIQUE,
  plan_id uuid,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'suspended'::text, 'cancelled'::text, 'trial'::text])),
  billing_cycle text NOT NULL DEFAULT 'monthly'::text CHECK (billing_cycle = ANY (ARRAY['monthly'::text, 'annual'::text])),
  user_count integer NOT NULL DEFAULT 1,
  modules_enabled ARRAY DEFAULT ARRAY['crm'::text],
  started_at timestamp with time zone NOT NULL DEFAULT now(),
  trial_ends_at timestamp with time zone,
  next_billing_date timestamp with time zone,
  last_billed_at timestamp with time zone,
  auto_renew boolean DEFAULT true,
  cancellation_reason text,
  cancelled_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT organization_subscriptions_pkey PRIMARY KEY (id),
  CONSTRAINT organization_subscriptions_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT organization_subscriptions_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES public.billing_plans(id)
);
CREATE TABLE public.organizations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  slug text UNIQUE,
  tier USER-DEFINED DEFAULT 'free'::org_tier,
  settings jsonb DEFAULT '{}'::jsonb,
  sector text DEFAULT 'real_estate'::text,
  business_type text,
  company_name text,
  gstin text,
  address_line_1 text,
  address_line_2 text,
  city text,
  state text,
  country text DEFAULT 'India'::text,
  pincode text,
  contact_number text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  onboarding_status USER-DEFINED NOT NULL DEFAULT 'pending'::onboarding_status_enum,
  caller_id text,
  currency text,
  currency_symbol text,
  custom_domain text UNIQUE,
  public_profile_enabled boolean DEFAULT false,
  website_config jsonb DEFAULT '{"font": "Inter", "theme": "modern", "sections": [], "primaryColor": "#000000"}'::jsonb,
  CONSTRAINT organizations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.payment_methods (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  type USER-DEFINED DEFAULT 'card'::payment_method_type,
  last4 text,
  brand text,
  expiry_month integer,
  expiry_year integer,
  is_default boolean DEFAULT false,
  gateway_customer_id text,
  gateway_payment_method_id text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT payment_methods_pkey PRIMARY KEY (id),
  CONSTRAINT payment_methods_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.payment_transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  invoice_id uuid,
  payment_gateway text NOT NULL CHECK (payment_gateway = ANY (ARRAY['razorpay'::text, 'stripe'::text, 'manual'::text])),
  gateway_order_id text,
  gateway_payment_id text,
  gateway_signature text,
  amount numeric NOT NULL,
  currency text NOT NULL DEFAULT 'INR'::text,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'authorized'::text, 'captured'::text, 'failed'::text, 'refunded'::text])),
  failure_reason text,
  payment_method text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT payment_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT payment_transactions_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT payment_transactions_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES public.billing_invoices(id)
);
CREATE TABLE public.pipeline_stages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  pipeline_id uuid,
  name text NOT NULL,
  order_index integer NOT NULL DEFAULT 0,
  color text DEFAULT '#cbd5e1'::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT pipeline_stages_pkey PRIMARY KEY (id),
  CONSTRAINT pipeline_stages_pipeline_id_fkey FOREIGN KEY (pipeline_id) REFERENCES public.pipelines(id)
);
CREATE TABLE public.pipelines (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid,
  name text NOT NULL,
  is_default boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT pipelines_pkey PRIMARY KEY (id),
  CONSTRAINT pipelines_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  organization_id uuid,
  full_name text,
  email text,
  phone text,
  avatar_url text,
  metadata jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  role USER-DEFINED DEFAULT 'employee'::user_role,
  manager_id uuid,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_manager_id_fkey FOREIGN KEY (manager_id) REFERENCES public.profiles(id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id),
  CONSTRAINT profiles_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.projects (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid,
  name text NOT NULL,
  description text,
  address text,
  status text DEFAULT 'active'::text,
  metadata jsonb,
  image_url text,
  image_path text,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  total_units integer DEFAULT 0,
  available_units integer DEFAULT 0,
  sold_units integer DEFAULT 0,
  reserved_units integer DEFAULT 0,
  unit_types jsonb,
  show_in_inventory boolean DEFAULT true,
  project_status text DEFAULT 'planning'::text,
  public_visibility boolean DEFAULT false,
  possession_date date,
  completion_date date,
  city text,
  state text,
  country text DEFAULT 'India'::text,
  pincode text,
  locality text,
  landmark text,
  is_draft boolean DEFAULT false,
  archived_at timestamp with time zone,
  archived_by uuid,
  min_price numeric,
  max_price numeric,
  is_archived boolean DEFAULT false,
  CONSTRAINT projects_pkey PRIMARY KEY (id),
  CONSTRAINT projects_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT projects_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT projects_archived_by_fkey FOREIGN KEY (archived_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.property_features (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  property_id uuid,
  feature_name text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT property_features_pkey PRIMARY KEY (id),
  CONSTRAINT property_features_property_id_fkey FOREIGN KEY (property_id) REFERENCES public.units(id)
);
CREATE TABLE public.property_images (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  property_id uuid,
  url text NOT NULL,
  is_featured boolean DEFAULT false,
  order_index integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT property_images_pkey PRIMARY KEY (id),
  CONSTRAINT property_images_property_id_fkey FOREIGN KEY (property_id) REFERENCES public.units(id)
);
CREATE TABLE public.saved_payment_methods (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  payment_gateway text NOT NULL DEFAULT 'razorpay'::text,
  gateway_customer_id text,
  gateway_token_id text,
  card_brand text,
  last4 text,
  expiry_month integer,
  expiry_year integer,
  is_default boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT saved_payment_methods_pkey PRIMARY KEY (id),
  CONSTRAINT saved_payment_methods_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.subscription_addons (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  description text,
  addon_type text NOT NULL,
  price_inr numeric NOT NULL,
  price_usd numeric NOT NULL,
  billing_frequency text DEFAULT 'monthly'::text CHECK (billing_frequency = ANY (ARRAY['monthly'::text, 'yearly'::text, 'one_time'::text])),
  available_for_plans ARRAY DEFAULT ARRAY['pro'::text],
  features jsonb DEFAULT '{}'::jsonb,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT subscription_addons_pkey PRIMARY KEY (id)
);
CREATE TABLE public.subscription_plans (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  description text,
  price_monthly numeric DEFAULT 0,
  price_yearly numeric DEFAULT 0,
  features jsonb NOT NULL DEFAULT '{}'::jsonb,
  is_active boolean DEFAULT true,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT subscription_plans_pkey PRIMARY KEY (id)
);
CREATE TABLE public.subscriptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  plan_id uuid NOT NULL,
  status USER-DEFINED DEFAULT 'active'::subscription_status,
  billing_cycle USER-DEFINED DEFAULT 'monthly'::billing_cycle,
  current_period_start timestamp with time zone DEFAULT now(),
  current_period_end timestamp with time zone DEFAULT (now() + '1 mon'::interval),
  cancel_at_period_end boolean DEFAULT false,
  cancelled_at timestamp with time zone,
  trial_ends_at timestamp with time zone,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT subscriptions_pkey PRIMARY KEY (id),
  CONSTRAINT subscriptions_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT subscriptions_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES public.subscription_plans(id)
);
CREATE TABLE public.towers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid,
  project_id uuid,
  name text NOT NULL,
  total_floors integer NOT NULL DEFAULT 10,
  units_per_floor integer NOT NULL DEFAULT 4,
  description text,
  metadata jsonb DEFAULT '{}'::jsonb,
  order_index integer DEFAULT 0,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT towers_pkey PRIMARY KEY (id),
  CONSTRAINT towers_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT towers_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT towers_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.unit_configs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  organization_id uuid,
  category text NOT NULL CHECK (category = ANY (ARRAY['residential'::text, 'commercial'::text, 'land'::text])),
  property_type text NOT NULL,
  config_name text,
  carpet_area numeric,
  built_up_area numeric,
  super_built_up_area numeric,
  plot_area numeric,
  transaction_type text NOT NULL CHECK (transaction_type = ANY (ARRAY['sell'::text, 'rent'::text, 'lease'::text])),
  base_price numeric,
  created_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  updated_at timestamp with time zone DEFAULT now(),
  updated_by uuid,
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT unit_configs_pkey PRIMARY KEY (id),
  CONSTRAINT unit_configs_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT unit_configs_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id),
  CONSTRAINT unit_configs_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT unit_configs_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.units (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid,
  project_id uuid,
  base_price numeric NOT NULL,
  bedrooms integer,
  bathrooms integer,
  status text NOT NULL DEFAULT 'available'::text,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  unit_number text,
  metadata jsonb DEFAULT '{}'::jsonb,
  archived_at timestamp with time zone,
  archived_by uuid,
  tower_id uuid,
  facing text,
  floor_rise_price numeric DEFAULT 0,
  plc_price numeric DEFAULT 0,
  carpet_area numeric,
  built_up_area numeric,
  super_built_up_area numeric,
  floor_number integer DEFAULT 1,
  lead_id uuid,
  config_id uuid,
  transaction_type text,
  total_price numeric DEFAULT 0,
  plot_area numeric DEFAULT 0,
  balconies integer DEFAULT 0,
  is_corner boolean DEFAULT false,
  is_vastu_compliant boolean DEFAULT false,
  possession_date date,
  completion_date date,
  construction_status text CHECK (construction_status = ANY (ARRAY['under_construction'::text, 'ready_to_move'::text, 'completed'::text])),
  updated_by uuid,
  is_archived boolean DEFAULT false,
  CONSTRAINT units_pkey PRIMARY KEY (id),
  CONSTRAINT properties_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT properties_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT properties_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT properties_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES public.leads(id),
  CONSTRAINT fk_properties_tower FOREIGN KEY (tower_id) REFERENCES public.towers(id),
  CONSTRAINT units_config_id_fkey FOREIGN KEY (config_id) REFERENCES public.unit_configs(id),
  CONSTRAINT properties_archived_by_fkey FOREIGN KEY (archived_by) REFERENCES public.profiles(id),
  CONSTRAINT units_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.usage_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  feature_key text NOT NULL,
  usage_count integer DEFAULT 0,
  period_start date NOT NULL,
  period_end date NOT NULL,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT usage_logs_pkey PRIMARY KEY (id),
  CONSTRAINT usage_logs_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.website_templates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  description text,
  thumbnail_url text,
  config jsonb NOT NULL,
  is_active boolean DEFAULT true,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT website_templates_pkey PRIMARY KEY (id),
  CONSTRAINT website_templates_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.websocket_servers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  url text NOT NULL UNIQUE,
  is_active boolean DEFAULT true,
  status text DEFAULT 'pending'::text,
  last_verified_at timestamp with time zone,
  priority integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT websocket_servers_pkey PRIMARY KEY (id)
);